name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant gradlew permission
        run: chmod +x android-app/gradlew

      - name: Build APK
        run: |
          cd android-app
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AlKhanjar-APK
          path: android-app/app/build/outputs/apk/debug/app-debug.apk
